# Generated by Django 6.0.2 on 2026-02-11 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='food_image',
            field=models.ImageField(blank=True, null=True, upload_to='food_images'),
        ),
        migrations.AddField(
            model_name='userorderactions',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
    ]
