# Generated by Django 6.0.2 on 2026-02-12 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_organization'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserOrderActions',
            new_name='UserOrderAction',
        ),
    ]
